import = [
  # "~/.config/alacritty/themes/themes/solarized_light.toml"
  "~/.config/alacritty/themes/themes/solarized_light.toml"
]

shell = {program = "/usr/bin/tmux", args = ["new-session", "-As", "main"]}

[font]
size = 27

[window]
decorations = "None"
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"
